### ISSUE TITLE
Bug in PrimeField for Multiplication operation

### ISSUE THREAD

**Issue by jayavanth** [zkcrypto/ff#105]
Code:
```
#[macro_use]
extern crate ff;

#[derive(PrimeField)]
#[PrimeFieldModulus = "18446744069414584321"]
#[PrimeFieldGenerator = "7"]
#[PrimeFieldReprEndianness = "little"]
struct Fpx([u64; 2]);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    pub fn test() {
        let val1: Fpx = Fpx([3u64, 0u64]);
        let val2: Fpx = Fpx([7u64, 0u64]);
        let sum_a = val1 + val2;
        let sub_a = val1 - val2;
        let mul_a = val1 * val2;
        assert_eq!(10u64, sum_a.0[0], "Add fails");
        assert_eq!(18446744069414584317u64, sub_a.0[0], "Sub fails");
        assert_eq!(21u64, mul_a.0[0], "Mul fails");
    }
}


```

Output:
---- tests::test stdout ----
thread 'tests::test' panicked at 'assertion failed: `(left == right)`
  left: `21`,
 right: `90194313195`: Mul fails', src/lib.rs:23:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I noticed that `90194313195` is `21` in Montgomery form. Is there a way to fix it?

**Comment by tarcieri** [comment]
I think the problem is the internal representation of the field element is in Montgomery form, but you're directly setting the internal representation rather than converting into Montgomery from (and out of Montgomery form when you're getting the results for comparison).

Try doing:

```rust
        let val1 = Fpx::from(3u64);
        let val2 = Fpx::from(7u64);
```

...and then use `fe.to_repr()` to get the results, e.g.

```rust
assert_eq!(10, sum_a.to_repr().0[0], "Add fails");
```

**Comment by Nashtare** [comment]
Completing @tarcieri's answer, I think the `Repr` type of your field, from the derived implementation of `PrimeField` would be an array of 16 bytes, so the comparison works so long your result fits in 8 bits. For larger values, you'd need to either reconstruct it (bit ugly), or compare directly:

```rust
let expected = Fpx::from(3u64 + 7);
assert_eq!(expected, sum_a, "Add fails");
```

**Comment by jayavanth** [comment]
Thank you both!

How do I call `to_repr()`? Since the Fpx variables are still a struct?

Yes the numbers I have are u64 so I think reconstruction seems like the best option for me. I've noticed that when I call this 
```
  // From Winterfell
    fn as_int(&self) -> Self::PositiveInteger {
        let x = self.0;
        let (a, e) = x.overflowing_add(x << 32);
        let b = a.wrapping_sub(a >> 32).wrapping_sub(e as u64);

        let (r, c) = 0u64.overflowing_sub(b);
        r.wrapping_sub(0u32.wrapping_sub(c as u32) as u64)
    }
```
```
math::fields::f64::BaseElement; // from Winterfell
BaseElement::from_mont(ff_mul.0[0]).as_int();
```
I get the canonical form back. However if I do more mults I'll need to call them as many times like this

```
BaseElement::from_mont(BaseElement::from_mont(ff_mul2.0[0]).as_int()).as_int()
```

Is this the reconstruction ugliness you were referring to?

**Comment by jayavanth** [comment]
Also if I do addition on top of it, Reducing twice doesn't work as well and the values are different
```
let mul_a = val1 * val2 * val3 + val1;

BaseElement::from_mont(BaseElement::from_mont(mul_a.0[0]).as_int()).as_int()
```

**Comment by tarcieri** [comment]
> How do I call to_repr()? 

@jayavanth the `PrimeField` trait provides `to_repr`, and you're deriving it for the `Fpx` struct. So just call `fpx.to_repr()` when you have the `PrimeField` trait in scope

**Comment by jayavanth** [comment]
ok I think I understand it now. **Thank you so much!** I can store and retrieve now by using the to_repr(). I just have to reconstruct the 16 u8 bytes into [u64;2]
