### ISSUE TITLE
Annoying `Default` requirement for PrimeField::Repr associated type

### ISSUE THREAD

**Issue by CPerezz** [zkcrypto/ff#108]
I'm currently trying to implement `Pluto-Eris` see: https://github.com/daira/pluto-eris

It turns out, since `PrimeField` trait requires `Default` to be implemented for the associated trait `Repr`, Pluto and Eris can't be implemented as, as today, the Rust language doesn't impl `Default` for any array larger than `32`.

**Comment by CPerezz** [comment]
I know this implies breaking the API. So not pushing a PR yet as I presume this will require discussion.

cc: @str4d

**Comment by tarcieri** [comment]
`TryFrom<&[u8]>` might be a better option than `Default`

**Comment by CPerezz** [comment]
At this point I do also wonder why don't we add a `min_const_generics` feature under a feature flag so that this does not happen.

**Comment by CPerezz** [comment]
@tarcieri that's super unfortunate lol... I thought this was doable already.. Thanks for the info BTW! An interesting-to-read issue definitely!

Not sure how to proceed here. But this is definitely a blocker for bringing Pluto-Eris to `halo2curves` repo.

**Comment by tarcieri** [comment]
I think the `Default` bound exists to support using `let mut repr = T::default()` and then using the `AsMut` bound to fill it for constructing the values, but it would probably be better to support `TryFrom<&[u8]>` which would avoid both the `Default` bound and mutability.

**Comment by str4d** [comment]
You need to use a wrapper type, a la `FieldRepr([u8; 48])`, on which you can implement `Default`. This is how we've implement it everywhere else that this is needed. It won't be necessary once const generic addition is possible.

**Comment by CPerezz** [comment]
Ohhh that's true... How did I not see this..

Thanks @str4d! Closing this then!
