### ISSUE TITLE
ff_derive is not updated on crates.io

### ISSUE THREAD

**Issue by keyvank** [zkcrypto/ff#17]
` + ?Sized` exists in `ff` but not in `ff_derive` (On crates.io, local version is fine), this has brought compilation problems in `zkcrypto/pairing` even after adding `?Sized` constraint to the `random()` functions' type parameters.
Maybe try updating `ff_derive`'s version from `0.4.0` to `0.4.1`?
Thanks!

**Comment by dignifiedquire** [comment]
@ebfull ping
