### ISSUE TITLE
Remove fmt::Display bound on Field?

### ISSUE THREAD

**Issue by tarcieri** [zkcrypto/ff#37]
(NOTE: this question applies to the `group` crate traits like `Group` as well, but I thought I'd start here)

The `ff::Field` trait bounds on both `fmt::Debug` and `fmt::Display`.

Looking at `bls128_381`, it seems all the `Display` impls are equivalent to `Debug`:

https://github.com/zkcrypto/bls12_381/blob/0d2c06d/src/scalar.rs#L33-L37

So why not just bound on `Debug`?

My main motivation for requesting this is I feel `Display` is something I want to add when there's a somewhat well-defined string representation of a given type, e.g. something a human would reasonably try to compare with a similarly printed string representing the same object, but output from a different library.

With the blanket impl of `ToString` for `T: Display`, I also like to make sure that if a corresponding `FromStr` impl is ever added to the type, it can round trip the output of `Display`/`ToString`.

**Comment by str4d** [comment]
Yes, this makes sense 🙂
