### ISSUE TITLE
Add `Field: ConstantTimeEq` bound

### ISSUE THREAD

**Issue by str4d** [zkcrypto/ff#62]
`Field` is already bound on `ConditionallySelectable`, so trait implementors are already required to pull in `subtle`. Having this bound would have simplified #61.

This constricts the `Field` definition, so requires a minor release.

**Comment by tarcieri** [comment]
As it were, the @RustCrypto `elliptic-curve` crate already enforces this bound: https://docs.rs/elliptic-curve/0.10.5/elliptic_curve/trait.ScalarArithmetic.html
