### ISSUE TITLE
`bitvec` v1.0

### ISSUE THREAD

**Issue by tarcieri** [zkcrypto/ff#70]
Would be nice to get a `bitvec` bump now that 1.0 is out:

https://crates.io/crates/bitvec/1.0.0

**Comment by str4d** [comment]
This requires an MSRV bump, so I will be coordinating this across the various repos in a few weeks (once we're done with `zcashd 4.7.0`).

**Comment by str4d** [comment]
We are now finally done with `zcashd 4.7.0` **sigh** so I am back to coordinating this.
