### ISSUE TITLE
derive(Copy) vs ZeroizeOnDrop

### ISSUE THREAD

**Issue by rillian** [zkcrypto/ff#77]
Something of a usage question. We're using zkcrypto/ff to derive a prime field for a shared-secret implementation, and also wanted to derive `ZeroizeOnDrop` from the [zeroize crate](https://docs.rs/zeroize/1.5.4/zeroize/) to limit the time key material is available in memory. However this conflicts with PrimeField's `Copy` trait, necessitating manual `.zeroize()` method calls which are more expensive to review.

Is the blanket `Copy` necessary? What's the best practice here?

**Comment by tarcieri** [comment]
The `elliptic-curve` crate uses a newtype for this purpose: https://github.com/RustCrypto/traits/blob/e5b9920/elliptic-curve/src/ecdh.rs#L167-L170

It allows the inner field element to remain `Copy`, while also ensuring the value is zeroized on drop.

(now I see it should probably not have a `Zeroize` impl, and only zeroize the inner value on `Drop`, something I should correct)

**Comment by rillian** [comment]
Thanks, that certainly works. But what's the value of having the inner element `Copy`? Is that important for the arithmetic operator impls?

**Comment by rillian** [comment]
Ok, thanks for clarifying. We'll look at the wrapper-type and/or custom `ZeroizeOnDrop` impls.
